spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maoyanmovie?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hut.maoyanmovie.bean


/啊啊啊啊啊啊啊啊啊啊啊