spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maoyanmovie?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hut.maoyanmovie.bean


